### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nomadic-coding** [odoo/runbot#159]
Hi together

I just discovered this repository and I would like to try runbot but I can't figure out how to configure it correctly.
Just to start: I would like to know how I can configure the standard odoo repository to start a new build. From there I can work my way through.
A sample config and the command how to trigger the build would be really helpful.

Thank you so much!

![Selection_304](https://user-images.githubusercontent.com/38637556/61803921-4ffc2300-ae33-11e9-8892-ba56e57597a2.png)

**Comment by aliencrash** [comment]
@nomadic-coding add your github token, apart of that the rest is unknown.

**Comment by nomadic-coding** [comment]
@aliencrash where do I specify which version (10.0, 11.0, 12.0) the runbot builds should be?

**Comment by aliencrash** [comment]
When for what I understand this is based on you branch number. They will automatically detected. The main issue with runbot is that it's designed to work with modules inside a complete odoo repository tree if I understand correctly.

Related to nginx you probably have to look to the permission. but I was able to put this module creating the build as expected.

**Comment by Xavier-Do** [comment]
Runbot doesn't have any notion of version.

You have to specify the name of the executable on repo, in our case, odoo/odoo and odoo-dev/odoo are configured with server names set as **odoo-bin,openerp-server,openerp-server.py** odoo-bin is enough for last versions.
The addons path is set as **addons,odoo/addons** for server repo, and left empty for orther repo since addons folders are at root level usually. 
To cover previous version, manifest files are set to **__manifest__.py,__openerp__.py**

If you are using odoo/odoo repo as base, this is the configuration you will want to keep it disabled or runbot will build everything.

Then you can add another repo with a dependency on odoo/odoo, respecting branchname convention. If you want to test your custom addon in saas-12.3, simply name your branch saas-12.3-destription-of-feature (or simply saas-12.3) 

You can use poll mode, or to avoid to spam fetch to github, use the hook mode on repo, but you will need to add webhook on github repo so that github will notify your runbot everytime a new commit is pushed.

**Comment by aliencrash** [comment]
> Runbot doesn't have any notion of version.
> 
> You have to specify the name of the executable on repo, in our case, odoo/odoo and odoo-dev/odoo are configured with server names set as **odoo-bin,openerp-server,openerp-server.py** odoo-bin is enough for last versions.
> The addons path is set as **addons,odoo/addons** for server repo, and left empty for orther repo since addons folders are at root level usually.
> To cover previous version, manifest files are set to ****manifest**.py,**openerp**.py**
> 
> If you are using odoo/odoo repo as base, this is the configuration you will want to keep it disabled or runbot will build everything.
> 
> Then you can add another repo with a dependency on odoo/odoo, respecting branchname convention. If you want to test your custom addon in saas-12.3, simply name your branch saas-12.3-destription-of-feature (or simply saas-12.3)
> 
> You can use poll mode, or to avoid to spam fetch to github, use the hook mode on repo, but you will need to add webhook on github repo so that github will notify your runbot everytime a new commit is pushed.

What could be useful maybe it a configuration example, for repository and runbot.

**Comment by skh-sw** [comment]
I have created a runbot rep as follows in Odoo 11 but I am unable to find the builds, There are no scheduled actions in the system to build this repo and I cannot find the action/button to trigger the builds.

![image](https://user-images.githubusercontent.com/52596412/66367173-8b2ade80-e9ac-11e9-8b68-c0c3fa831f1d.png)

How can we trigger builds for this repo? Do we have to define build hosts?

**Comment by Xavier-Do** [comment]
Build host will be create automatically, in your case you may have only one host. 
Anyway, you need to create  cron jobs that will search for new commit in git, and another to tests, and change build states. 

Caution: runbot is using odoo 11 but will only work with python 3

The two crons methos to use are in repo.py:
- _cron_fetch_and_schedule
- _cron_fetch_and_build

Those are long running cron since we have a lot of worker in our infrastructure, you may not need them.

**Long running cron solution:** 
You need to call each method in individual ir.cron, executing each x seconds. You need to specify the host name (socket.fqdn() in python) and give limit_time_real or limit_time_real_cron of at least ~600 seconds. 

**Simplest way without running cron**
You can use a simplification of those crons
1. Fetch cron:
``` python3
repos = self.search([('mode', '!=', 'disabled')])
repos._update(force=False)
repos._create_pending_builds()
```
This is basivally all you need to update your github repo and find new commits, I would execute that at most every x minutes since if your repo is on poll mode, you will fetch each time.

2. Testing cron:

``` python3
host = self.env['runbot.host']._get_current()
self.env['runbot.repo']._source_cleanup()
self.env['runbot.build']._local_cleanup()
repos = self.search([('mode', '!=', 'disabled')])
repos._scheduler(host)
self._reload_nginx()
```
This can be execute more often, something like 10 seconds is perfect. This will move build from pending to testing, and testing to running/done depending on the config used. 

You may want to customize this code depending on you need, to update disabled repo maybe. 

Documentation isn't our priority but we are keeping that in mind. 

Keep in mind to give enough cron worker to your instance too.

**Comment by aliencrash** [comment]
It's there any place where we can read how to configure the runbot now?

**Comment by Xavier-Do** [comment]
Runbot is mainly use internally and documentation is not our priority. Still, we are please to hear that you are interested by this project, and we are currently trying to make it easier to configure. I hope we will have some time to write some documentation once most wip features are stabilized and migration to odoo 13.0 is done.

You can ask us your questions, any discussion about runbot will be a good start for a future documentation.

**Comment by aliencrash** [comment]
Ok. 

1. What should be filled here Runbot URI for build logs
2. Now in repository can you explain what this 3 fields are for?
![imagem](https://user-images.githubusercontent.com/10322162/67588166-5610e100-f74d-11e9-96e7-e5a34d403eaa.png)
3. How should the structure of custom repository be configured to allow to runbot custom modules. I noticed that in general the used structure is  /addons_project/ your_module. that means also that you have to have all your modules inside the /addons_project.

**Comment by Xavier-Do** [comment]
1. Runbot uri:
postgres://user:password@domain.com/runbot
This user have restricted right on should only by usable by whitelisted ip . This is --log-db parameter of odoo, allowing all log level 25+ to appear on build page. 

2. Note: I justed pushed a commit to remove duplicate addons files description, the second is actually addons path.

Configuration we are using for odoo
![image](https://user-images.githubusercontent.com/35262360/67591083-e1de3980-f75c-11e9-92c0-58c4f4b89f79.png)


Configuration we are using for enterprise, aka addons only repo:
![image](https://user-images.githubusercontent.com/35262360/67591748-65e4f100-f75e-11e9-95ee-a7ca195eb93f.png)

To know where the executable is located, runbot will search for first repo (in repo list+ repo dependencies) with a server files defined. Then he will search in repo path if one of this server file exist. If you decide to run an app with a run.py at root, you will need to define run.py as server file. In our runbot config, we have the different server files used in odoo history but for last version odoo-bin is enough
Manifest files (previously first Addons files) are mainly use to define if a directory in addons path is a addon or not. 
Addons path are given as --addons-path parameter to executable and are used to search for all addons. 

Odoo repo 

-  most addons directories are in addons/
-   some addons directories are in odoo/addons/ like base

Addons only repo: 
-  all addons directories are at repo root.

**Comment by aliencrash** [comment]
Thanks.
I have an addons that I'm trying to execute with runbot. As dependency repo I put Odoo repo. but I still get No repo found with defined server_files.

**Comment by Xavier-Do** [comment]
```python3
def _get_all_commit(self):
        return [Commit(self.repo_id, self.name)] + [Commit(dep._get_repo(), dep.dependency_hash) for dep in self.dependency_ids]

def _get_server_commit(self, commits=None):
        for commit in (commits or self._get_all_commit()):
            if commit.repo.server_files:
                return commit
        raise ValidationError('No repo found with defined server_files')
```

Either your dependency on build (/repo) is incorrect either you didn't specify server files on odoo repo.

**Comment by aliencrash** [comment]
This is my Odoo repo configuration
![imagem](https://user-images.githubusercontent.com/10322162/68397820-14802d00-0174-11ea-94f7-08e706943baa.png)

And this is my test module configuration
![imagem](https://user-images.githubusercontent.com/10322162/68398016-5f01a980-0174-11ea-8051-1167f6bf03b8.png)
can you advise me on what  I'm doing wrong?

**Comment by Xavier-Do** [comment]
Server files looks ok, as well as dependencies.

Can you check the dependency_ids that you have on the corresponding build? you can edit form view by adding this at the end.
```
<field name="dependency_ids">
    <tree>
        <field name="dependecy_repo_id"></field>
        <field name="dependency_hash"></field>
        <field name="closest_branch_id"></field>
        <field name="match_type"></field>
    </tree>
</field>
```
You should have one line with dependecy_repo_id being odoo/odoo.

Side note: The fact that the odoo repo is disabled may have an impact later, mainly because it is never updated. We may need to offer some tools to help to let repo create branch while disabling builds. I will maybe ads a no_auto_build on repo. For now it is possible to set an empty config on this repo.

**Comment by aliencrash** [comment]
It's completely empty.

**Comment by aliencrash** [comment]
I'm almost there. Now when  trying to create the build I'm having this. Dependencies are ok, my configuration is like in the previous screenshot. Any hint?


2019-11-11 10:27:03,535 139187 ERROR runbot odoo.addons.runbot.models.build: Failed to wake up build 16025-13-0-37ef98
Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/models/build.py", line 572, in _schedule
    self.env['runbot.build.config.step']._run_odoo_run(build, log_path)
  File "/home/odoo/runbot/runbot/models/build_config.py", line 263, in _run_odoo_run
    cmd = build._cmd(local_only=False)
  File "/home/odoo/runbot/runbot/models/build.py", line 903, in _cmd
    cmd = ['python%s' % py_version] + python_params + [os.path.join(server_dir, server_file), '--addons-path', ",".join(addons_paths)]
  File "/home/odoo/runbot/runbot/models/build.py", line 875, in _get_addons_path
    for addons_path in commit.repo.addons_paths.split(','):
AttributeError: 'bool' object has no attribute 'split'

**Comment by Xavier-Do** [comment]
"Failed to wake up build " should only appear if you click on the coffee mug button, it shouldn't be there in the default flow. 

Your trackback looks strange, _get_addons_path is called line 898 not 903. It is maybe linked to a non-restared database after a code update? 

Anyway, either your repo addons_path is null with shouldn't be the case since there is a default value to '' on addons_path or for any reason a Commit has a empty recordset as repo which looks impossible to me looking to the way it is computed and that all linked fields are required. 

Best solution would be to add some log in build.py line 875 to log commit.repo and commit.repo.addons_paths

**Comment by aliencrash** [comment]
After putting the log in build.py I found the issue. The problem is that my addons paths is empty in the custom module repository. The structure of the custom module is like  portal/module_1, portal/module_2 and portal/module_3.

**Comment by kos94ok-3D** [comment]
Hi, @Xavier-Do. Could you help me?
postgresql 9.6
try to run fork odoo13 without any changes
![изображение](https://user-images.githubusercontent.com/33932458/73284060-abe99f00-41fc-11ea-929e-5c2d6eadfa52.png)

**Comment by d-fence** [comment]
@kos94ok-3D Can you try with a newer version of porstgres and tell us if you still see this problem ?
If it's the case, you could open a new issue as it seems unrelated.
Thanks.

**Comment by kos94ok-3D** [comment]
@d-fence, thanks. It`s work with PostgreSQL 11

**Comment by ahilalix** [comment]
Hello,

I have repo with just submodules, can i use runbot with this config ?

thanks,
@d-fence @Xavier-Do

**Comment by Xavier-Do** [comment]
submodules? you mean modules maybe? 

Yes you can but it can be a little tricky to setup. We are glad to see the community using runbot and we are trying to make it possible, but since it isn't our priority, there is no install documentation for runbot and the default setup at install is not enough to make it work. I hope we will have the time to improve that in the future.

**Comment by ahilalix** [comment]
Thank you for your reply, submodules are modules on an others repos like OCA:
My community repo is like this :
![submodule](https://user-images.githubusercontent.com/51242096/77153569-40a0a880-6a9a-11ea-98f5-da705de09973.png)

When a run crons _cron_fetch_and_schedule and _cron_fetch_and_build I found server-tools and server-tools empty

Thanks

**Comment by obayit** [comment]
Hello @Xavier-Do I have a question, 
I was able to make runbot build my branches, but I can't make the URL for any build work. (e.g: **https://00038-master-d9d6e8.runbot.mydomain.com/?db=00038-master-d9d6e8-base** doesn't work)
How to configure nginx for runbot (with https)?

**Comment by gsk-rsf-o** [comment]
Found an answer [here](https://unix.stackexchange.com/a/291007/394990). I was missing this `proxy_set_header HOST $host;`

**Comment by gsk-rsf-o** [comment]
Found an answer [here](https://unix.stackexchange.com/a/291007/394990). I was missing this `proxy_set_header HOST $host;`

**Comment by aliencrash** [comment]
Hi, 
I've pushed the version 13.0, I already configured odoo repository. Wouldn't be suppose to get the branches?
If you give more orientation I could make the documentation and then every body could contribute.

**Comment by Xavier-Do** [comment]
I'm currently working on a new version of the runbot, so the documentation would be quickly outdated.
You have pushed the version 13? 
Anyway, maybe your repo is not in poll mode. You need to configure hooks if you are in hook mode.

**Comment by aliencrash** [comment]
I already have the hook configured, and integrated when there is a push the hook it's called. But even odoo repository I don't see branch creation.

**Comment by Xavier-Do** [comment]
It is impossible that odoo/odoo hooks your prod, what do you mean by odoo repository?

**Comment by aliencrash** [comment]
> It is impossible that odoo/odoo hooks your prod, what do you mean by odoo repository?

Sorry, the hook is in my repository. based on above conversation I configured the odoo repository   like this. 
![imagem](https://user-images.githubusercontent.com/10322162/79335017-3c40a180-7f19-11ea-80c8-48504c6e7d40.png)
The pull from odoo was done correctly. I already created the 2 crons that were suggested above. Then I created repository form my addons with hook. and the hook works. But I don't see any branch or build being created.
My settings 
![imagem](https://user-images.githubusercontent.com/10322162/79335257-9f323880-7f19-11ea-965c-93df56c76b7b.png)

**Comment by aliencrash** [comment]
I went to command line in runbot/static/repo/ and notice that my addons repository exists, but without content.

**Comment by Xavier-Do** [comment]
To be honest, the problem is that runbot is not fully designed to do that. (Even if we are trying to keep it as flexible as possible)
The problem is that with repo odoo is disabled, github fetch wont be done automatically.
You can either:
-Update manually the odoo/odoo repo in the cron (by removing the disable filter for _update in the cron
OR
- We added an automatic update hook on dependencies
```python3
 if not payload or event == 'push' or (event == 'pull_request' and payload.get('action') in ('synchronize', 'opened', 'reopened')):
    (repo | repo.dependency_ids).set_hook_time(time.time())
```
So in theory, if your other repo has a dependency on odoo and is in hook mode, it should trigger hook on odoo too, and fetch the repo. 

You need to check no_build on odoo/odoo repo (as it is) or you will have a lots of builds.

I don't know if it will work but I have the new runbot in mind now i'ts kind of difficult to switch from one logic to the other. I'll try to write some step by step documentation to setup the new runbot to test external module.

**Comment by aliencrash** [comment]
> To be honest, the problem is that runbot is not fully designed to do that. (Even if we are trying to keep it as flexible as possible)
> The problem is that with repo odoo is disabled, github fetch wont be done automatically.
> You can either:
> 
>     * Update manually the odoo/odoo repo in the cron (by removing the disable filter for _update in the cron
> 
> 
> OR
> 
>     * We added an automatic update hook on dependencies
> 
> 
> ```python
>  if not payload or event == 'push' or (event == 'pull_request' and payload.get('action') in ('synchronize', 'opened', 'reopened')):
>     (repo | repo.dependency_ids).set_hook_time(time.time())
> ```
> 
> So in theory, if your other repo has a dependency on odoo and is in hook mode, it should trigger hook on odoo too, and fetch the repo.
> 
> You need to check no_build on odoo/odoo repo (as it is) or you will have a lots of builds.
> 
> I don't know if it will work but I have the new runbot in mind now i'ts kind of difficult to switch from one logic to the other. I'll try to write some step by step documentation to setup the new runbot to test external module.

Your idea make sense. or may the pull could be on-demand with button if mode = disabled.

**Comment by aliencrash** [comment]
Would take to much to create a basic setup explanation or documentation? At least to fill the forms and put it working.

**Comment by Xavier-Do** [comment]
@aliencrash @nomadic-coding We added a setup documentation in the readme of the new runbot. We tried to take other users cases into account when developing this version and the given example explains how to test custom modules with odoo. Feel free to open another issue if you have questions on how to setup the new version and the readme is not enough.
