### ISSUE TITLE
forwardbot feedback should come from forwardbot

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#190]
odoo/odoo#36614: complaints about forward-port targets posted by mergebot user
odoo/odoo#36605: ping from forwardbot posted by mergebot user

/cc @nim-odoo @mart-e

**Comment by mart-e** [comment]
Ping can be included in the first message to avoid unnecessary messages.
(and yes it works, for instance I got the first message at https://github.com/odoo/odoo/pull/36394#issue-313781085)

**Comment by mart-e** [comment]
Also, is it needed to ping outside collaborators (who I hope do not have the rights for r+)
https://github.com/odoo/odoo/pull/36629#issuecomment-529926608

**Comment by xmo-odoo** [comment]
Not sure I understand what you mean. Ping is the same for internal and external collaborators, it's just that the ping is sent under the wrong user.

**Comment by mart-e** [comment]
I am saying if he is not an odoo employee (aka a member of the repository), the author does not need to be pinged on a PR for each version. He does not need what to do (and he probably does not need to do anything).
Or at least with another message than "ping"

**Comment by mreficent** [comment]
I think a good use of this tool should be as following:

Case 1 (normal usecase): in a PR, you do `robod.. r+`, then it merges normally as always. It means that the fix is trivial to forwardport and it doesn't need to keep watching. The fix will be forwardported eventually by kang-o in its periodical forwardports.

Case 2: in a PR, you do `robod.. r+ forwardbot+`, then after merging the PR, a new PR is opened doing forwardport of the commits of that PR to the next active branch. It would mean that you want to keep watching the forwardport, because probably it's a bit complicated and will need some adaptation via force push. Also, before merging, if you do forwardbot-, then it goes as case 1.

I think this way, the forwardbot is used in a controlled way, only when is necessary.

**Comment by mart-e** [comment]
@mreficent the goal of the forward port bot is to no longer make manual forward port. @KangOl will finally be free of periodical forwardport.
The main idea is that a fix should be ported to all versions as soon as possible and the author of the commit is the best person to adapt it to other versions.

**Comment by mreficent** [comment]
but there will be a lot of PRs from forwardbot. Literally overflooding, almost spam. For example, now, a fix in v10 will generate later 9 PRs (because there are 10 active branches).

**Comment by mart-e** [comment]
Yes, that is indeed what is going to happen. Doing manual forward port was not working anymore, it is very hard and error prone and only gets worse with Odoo increasing in size.
