### ISSUE TITLE
Delete FP branches automatically

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#230]
As of now, we've got ~320 -forwardport branches in odoo and ~80 in enterprise, most of which are likely linked to closed or deleted PRs.

This is still a very small minority of the dev branches (resp. 6700 and 3500) but we could automatically clean them up after a while.

Technically we could even clean up the branches of all merged PRs, as long as they live in -dev (fetch branches, filter against PR labels, delete matches). People who keep re-using branches might not be happy that we keep deleting their branches though...

/cc @Elkasitu @nim-odoo

**Comment by seb-odoo** [comment]
This would be very helpful.

As a side node, if you implement some kind of automation in all cases, I would like to point out that I always create branches in enterprise+themes even if I only have community diff in order to test all runbots, so it would be nice if it looked for the same name in all repos.

Is it really an issue for people keeping re-using branches? It will just tell them that their remote branch is gone and they can just push again to restore it (which they will do anyway if they add new changes on the same branch) .

**Comment by xmo-odoo** [comment]
> Is it really an issue for people keeping re-using branches? It will just tell them that their remote branch is gone and they can just push again to restore it (which they will do anyway if they add new changes on the same branch) .

If it's a cron which looks for the branches linked to PRs marked as merged, it's going to delete the branches every time they're recreated.

**Comment by Elkasitu** [comment]
the cron could just skip branches with a specific keyword in their name e.g. 13.0-fixes-**persistent**-adt

**Comment by seb-odoo** [comment]
This could be based on commit hash? Only delete the branch if the last commit on it is the commit that was existing at the time of the merge?
