### ISSUE TITLE
Support retargeting of closed PRs (& better handling of closed / merged PRs)

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#305]
* if a PR is retargeted while closed, robodoo should be aware / should update its target on reopening (basically it should update more than just the state & head)
  - should add logging in retarget and synchronise as sometimes bits get missed (e.g. that commits is now 1) and it's not clear where or why
* if a PR is reopened while merged, insult whoever reopened it, then close it right back

Others? /cc @rdeodoo @Xavier-Do

**Comment by rdeodoo** [comment]
I didn't experience any other issue that I can think of.
Once `if a PR is reopened while merged, insult whoever reopened it, then close it right back` is done, you can ping me if you need someone to approve :wink: 

The only think I had issue with is when you retarget an enterprise PR.
Since your dev branch name still contains the previous target branch, the runbot will still try to built it on it and it won't work obviously (eg `13.0-fix-test-rde` 'rebased' on 12.0 and PR retarget 12.0 on enterprise, runbot will always fail as it will try to build it on top of community 13.0 (branch name matching)).
But that's quite a corner case which is easily fixed by pushing a dev branch on community with the same name containing the code from the new target (eg pushing `13.0-fix-test-rde` containing the code of Odoo 12.0), not worth doing any magic.
Plus, that's not related to robodoo or fwbot, it is just about runbot.

**Comment by xmo-odoo** [comment]
> The only think I had issue with is when you retarget an enterprise PR.
> Since your dev branch name still contains the previous target branch, the runbot will still try to built it on it and it won't work obviously (eg `13.0-fix-test-rde` 'rebased' on 12.0 and PR retarget 12.0 on enterprise, runbot will always fail as it will try to build it on top of community 13.0 (branch name matching)).

That's more of a runbot issue for @Xavier-Do and @d-fence I'm pretty sure I can't do anything about it on the mergebot side.

**Comment by xmo-odoo** [comment]
@rdeodoo so after writing a test for this, turns out github doesn't allow retargeting closed PRs, and if a branch is updated the corresponding PR can't be reopened. So that's pretty cool.

**Comment by rdeodoo** [comment]
Oh, that must be preventing a lot of corner cases.
About my 'bug' for re-target enterprise branch, I don't think it is actually worth spending time on it as it is quite obvious to figure & fix when it happens (logs insta crash, easy to see among the few lines that it tried to built on top of the wrong community sticky branch, just have to push the same branch name on community dev).

**Comment by Xavier-Do** [comment]
We can catch the retarget event and update the runbot branch if not lost (it was an idea) but it will lead to strange result since the branch name will not match the target,  may lead to strange behavior like receiving different ci for the same hash. 

I'll create a task to handle retarget, but it is still a bad practice to have a pr target not matching branch name.

**Comment by rdeodoo** [comment]
> I'll create a task to handle retarget, but it is still a bad practice to have a pr target not matching branch name.

Yes and no.
It happens (rarely) that you decide to target another branch during the review or when the dev is already well started.
In those cases, you don't want to lose all the possible discussion and reviews the PR had just to change the branch you will merge it on.

So yes, it happens rarely, and most of the time you just close it and reopen it with the correct dev branch name since there is nothing on the PR yet.
But when you had multiple reviews and discussion, it is really bad to lose everything and merge the discussed feature on a new PR that won't contain any of the reviews.

But not worth any improvement IMO, easy to detect & solve when it happens, plus quite a rare case.
