### ISSUE TITLE
Fix override rights

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#420]
- [ ] manytomany_tags absolutely doesn't work for o2m, either have an m2m between partner and override rights, or don't display as tags
  - [ ] if m2m, check whether name_search works correctly (finds by context or repo name) so it's easy to search for e.g. `security` and get every ci/security override
- [ ] allow leaving repo out of override right to allow for all repos (in which case improve name_get display)

/cc @Xavier-Do were there other issues with the override stuff?

**Comment by Xavier-Do** [comment]
Adding a m2m between partner and ci would be enough I think, no need an override object if you remove the repo

- Make ci object searchable with a name_get instead of copying the context in the partner form
- Display the list of partner with override right on the ci object, and make this m2m editable so that we can add partner to a ci instead of adding ci to a partner (can be more convenient in some cases). 

Only suggestions, do as you want ;)
