### ISSUE TITLE
Skip Requirements

### ISSUE THREAD

**Issue by d-fence** [odoo/runbot#480]
## Problem

Odoo > =13.0 should be built with a pure Docker Focal **without installing the `requirements.txt`**.
But in that case:

- Changes in `requirements.txt` will not be tested anymore
- If a dev working on a new feature needs a new lib, it will not be installed by the  `requirements.txt` and all his builds are going to fail

## Current situation

- Build parameters have a flag [`skip_requirements`](https://github.com/odoo/runbot/blob/6279dfa442cb5d0cfe3e364534dc1d6b7697d23b/runbot/models/build.py#L55) that allows to skip the install of  [`requirements.txt`](https://github.com/odoo/runbot/blob/6279dfa442cb5d0cfe3e364534dc1d6b7697d23b/runbot/models/build.py#L929) that are in tested sources. This field is set to `False` by default, which means that **requirements are always installed**.
- Docker image templates also have the possibility to [install](https://github.com/odoo/runbot/blob/6279dfa442cb5d0cfe3e364534dc1d6b7697d23b/runbot/templates/dockerfile.xml#L140) the `requirements.txt` file from the corresponding branch on github.
 The runbot Docker Focal image does not install them (bionic image does).
- The Docker Focal image is tested against each Odoo sticky branch without installing any requirements (the python config sets the `skip_requirements`field to True). **It's green from 13.0 to master**.
- The Odoo Version 13.0 already uses the Docker Focal image but the requirements are installed (not ideal).
- 14.0 [fails with a warning](https://runbot.odoo.com/runbot/build/7157460) when using Docker Focal image because of the `requirements.txt`

**Comment by d-fence** [comment]
A solution may be to add a `skip_requirements` field on the Version object. That way, we could have version < 13.0 that install requirements and >= 13.0 that does not install requirements.

But that will not solve the two initial problems

@Xavier-Do any idea ?

**Comment by Xavier-Do** [comment]
We should keep installing requirements on test builds since it is a good way for a dev to add new lib when needed + fix the execution of a version in time: If requirements says 13.0 requires some version of a package it will test odoo with that version and catch potential use of a future feature not yet on this version that may break when used on an already installed environment. 

The use case of installing an old version on a new system is less critical and can be tested during nightly, IMAO. 
Merge -> use an environment as close as possible as when the version was released.
Nightlly -> Test old version with new environment (and new version with old environment. maybe) without requirements.

**Comment by d-fence** [comment]
As suggested, requireements are installed and a build without requirements is tested nightly.
