### ISSUE TITLE
Add PR numbers to all rebased commits instead of just the last one.

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#482]
Maybe setting the "current PR" as related, and ignoring the actually related PRs.

Git and related tools make it difficult to find the "merge tip" from one of the commits it merges, which thus makes it difficult to track down a PR having contained multiple commits from one of its commits post integration.

As a result some teams have taken upon themselves to manually add every PR in the batch to every commit, which then spams the PR with pingbacks on every update to the related PRs.

Linking every commit back to the source PR would make that somewhat better as it would then allow finding the rest of the information (e.g. links related PRs, tasks, ...).

Sadly while I was considering *notes* I was reminded that they suck, and github stripped notes support back in 2014.

Probably requires a few adjustments to `_build_merge_message`:

* Don't add `Related` if it's already in the body (similar to the `Closes` message)
* Mebbe don't add the `signed-off-by` to non-tip commits?
* When searching for existing PRs, might be useful to also match "full" github URLs *and rewrite them*? It looks like github will reformat them (at least in PR messages) but will not generate crosslinks e.g. odoo/odoo#63628 the enterprise link is a full URL, it's rewritten to a reference, but on the linked PR there's no link back.

**Comment by rdeodoo** [comment]
Not sure how are other teams working, but this one seems so much critical in our case.
Not a single PR history is not completely noised/destroyed/made useless with those PR references.

Most of the times, you are reviewing a PR and don't even see the previous review from a colleague that was done 2 days before, it is just hidden behind 
![image](https://user-images.githubusercontent.com/30048408/120206059-0187ee80-c22b-11eb-9404-cfbb775679de.png)
that you can only unfold 50 at a times, even if there was only 2 'real' messages.

It is problematic during the review: you have to unfold hundreds of noise notifications to be able to see real content (eg review or discussion)
It is problematic later when blaming a commit, if there is an explanation/a debate or anything useful on the PR, it is also hidden.

Right now, we don't want to stop writing initially the PR references, as we don't want to forget it when the PR is r+'d

If we could at least have a warning if a commit has no PR reference at r+ time, we would at least be able to stop directly writing the PR reference (that is noising the PR) since we would know that even if we forgot it, we will notice at r+, then we can r-, write it, and r+.
Otherwise, I guess we will have to write 'fake' reference, eg something like `PR-14567` instead of the `#12345` so we are sure to be able to retrieve the commit PR when blaming, and won't noise the PR.

Well, ideally Github should have a button to hide push-force and PR references from the PR thread, so you can focus on actual messages.

**Comment by rdeodoo** [comment]
If it is not planed to add the same behavior on multi-commit PR than single commit PR, can we at least add a hint inside the robodoo message when we set the rebase method?
Instead of
```
Merge method set to rebase and fast-forward
```
just something like
```
Merge method set to rebase and fast-forward (as there is multiple commits, PRs references won't be added automatically to your commits, don't forget to add it yourself)
```
or whatever will do

For the record, we changed our workflow and just stopped adding the references before merge time (or we add fake reference like PR-12345) which stopped the notification noise on PR threads.
We just need to pay attention to not forget to write it before r+ in case or multi-commit PR (as it will be done automatically on single commit PR)
That hint would help us not forgetting it.

**Comment by xmo-odoo** [comment]
> If it is not planed to add the same behavior on multi-commit PR than single commit PR

If it was not planned I'd have closed the issue as wontfix. But I can close it now and stop working on this if you want.

**Comment by xmo-odoo** [comment]
Also no I'm not going to add a message *telling* people they *must* add PR references to their commits when they have no reason to if they don't want to (not that anyone reads the fwbot's messages).

**Comment by rdeodoo** [comment]
> But I can close it now and stop working on this if you want.

That's obviously not what I meant. I was suggesting a temporary 'workaround' while the mergebot adds the PR references to commits on multi-commit PR.
Then I thought the rebase setting step was a good entry point to show a message to not forget it.
It has been 3 months without any news (not saying it is not normal or it is easy/fast to do, or a priority), I don't think my proposal was rude in any way.. Sorry if you took it that way.
I figured this was either lowest priority, either technically problematic to do, so I suggested that workaround..

> they **must** add PR references to their commits when they have no reason to if they don't want to (not that anyone reads the fwbot's messages).

That was just an exemple, ofc the message could just be a hint ("if you want to") and not a "you have to".
Anyway, is there any good reason why a commit would not reference its PR? (If there is a task-xxx why not, you can find the PR from there, but generally when there is no PR, there is no task either)

**Comment by rdeodoo** [comment]
:tada: Thank you !
