### ISSUE TITLE
error > push + retry = approved?

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#83]
Currently, pushing & retrying a PR in error will automatically mark it as "ready" (and re-stage it). This may or may not be the correct behaviour, I'm conflicted: it means the retry will skip pre-staging runbot despite the code has changed, OTOH one could expect the changes to be minor and the PR could be explicitly r-'d then r+'d to perform the entire cycle?

Alternatively, push + retry on a PR could move it to approved (would still have to pass runbot but would be immediately re-staged afterwards) or even opened (the latter is what happened when updating a PR which is neither closed nor in an error state)

/cc @odony @rco-odoo

**Comment by odony** [comment]
From a pure R&D point of view, the fastest option is probably best, but there is a theoretical security risk in allowing an updated PR to be staged without re-approval, so going back to "opened" might be more correct.

What's the sequence of stages?  `opened > red > green > approved > staged > done` ?

If that's correct, and because most `push` events are supposed to happen before the approval "gate", then pushing after `approved` should probably reset back to opened (and retrying would be ignored). It's quite unlikely to happen anyway. Or isn't it? What's the use case?

Side questions:
- Do we have any chance of race conditions between approval and staging? Or do we freeze the approved revision so that only this revision can be merged?
- Do we know who pushed? If we do, we could handle an "external" push differently from one coming from a registered team member...

**Comment by xmo-odoo** [comment]
> What's the sequence of stages? opened > red > green > approved > staged > done ?

![states](https://user-images.githubusercontent.com/7571158/51920848-768e5380-23e6-11e9-8edd-db8a7544c7e8.png)

> pushing after approved should probably reset back to opened (and retrying would be ignored). It's quite unlikely to happen anyway. Or isn't it? What's the use case?

That's currently the case in general, just not for PRs in error, they remain in error rather than get reset to "open", and "retry" moves a PR from error to ready.

> Do we have any chance of race conditions between approval and staging? Or do we freeze the approved revision so that only this revision can be merged?

The mergebot works with a stored head, so there should be no race condition there. It's possible the runbot will stage the pre-update revision and not notice the update though, I think.

> Do we know who pushed? If we do, we could handle an "external" push differently from one coming from a registered team member...

IIRC github always provides a "sender" attribute with whoever triggered the event so this should be knowable.

**Comment by odony** [comment]
Thanks for the detailed info! Then I guess pushing while in `error` stage should behave just like the general case (back to `open`). I assume most retries would be for timeouts or false positives, and would not require a push anyway.
And if easy enough, we could make an exception if the push comes from a registered organization member, where we would fast track from `error` to `approved`, on the assumption that it's a minor bugfix for the PR. Someone could still `r-` after the push if another review is desired.
